# This file intentionally left blank

# WS2812_DRIVER = vendor
VIAL_ENABLE = yes
VIA_ENABLE = yes
QMK_SETTINGS = yes
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes
TAP_DANCE_ENABLE = yes
ENCODER_MAP_ENABLE = yes


I2C_DRIVER_REQUIRED = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
